#pragma once





#define static_spell static constexpr const HashedString
static_spell soul_link("Soul Link");
static_spell decimation_spell("Decimation");
static_spell soul_fire_spell("Soul Fire");
static_spell metamorphosis_spell("Metamorphosis");
static_spell immolation_aura_spell("Immolation Aura");
static_spell demonic_empowerment_spell("Demonic Empowerment");

static_spell CALL_OF_THE_ELEMENTS("Call of the Elements");
static_spell fire_nova_spell("Fire Nova");
static_spell lava_lash_spell("Lava Lash");
static_spell lava_sweep_spell("Lava Sweep");
static_spell stormstrike_spell("Stormstrike");

static_spell molten_core_spell("Molten Core");
static_spell incinerate_spell("Incinerate");
static_spell spirit_of_redemption("Spirit of Redemption");
static_spell glyph_of_blocking("Glyph of Blocking");
static_spell glyph_of_revenge("Glyph of Revenge");
static_spell fishing_spell("Fishing");
static_spell sacred_shield_spell("Sacred Shield");
static_spell divine_plea_spell("Divine Plea");
static_spell holy_shield_spell("Holy Shield");
static_spell divine_sacrifice_spell("Divine Sacrifice");
static_spell blessing_of_sanctuary_spell("Blessing of Sanctuary");
static_spell greater_blessing_of_sanctuary_spell("Greater Blessing of Sanctuary");
static_spell hand_of_reckoning_spell("Hand of Reckoning");
static_spell righteous_defense_spell("Righteous Defense");
static_spell consecration_spell("Consecration");
static_spell exorcism_spell("Exorcism");
static_spell hammer_of_wrath_spell("Hammer of Wrath");
static_spell art_of_war_spell("The Art of War");
static_spell crusader_strike_spell("Crusader Strike");
static_spell divine_storm_spell("Divine Storm");
static_spell holy_wrath_spell("Holy Wrath");
static_spell judgement_of_light_spell("Judgement of Light");
static_spell seal_of_command_spell("Seal of Command");
static_spell righteous_fury("Righteous Fury");
static_spell blessing_of_might("Blessing of Might");
static_spell hammerstorm("Hammerstorm");
static_spell lights_hammer("Light's Hammer");
static_spell sanct_blessing_of_might("Sanctified Blessing of Might");
static_spell sanct_blessing_of_kings("Sanctified Blessing of Kings");
static_spell sanct_blessing_of_wisdom("Sanctified Blessing of Wisdom");
static_spell sanct_blessing_of_sanctuary("Sanctified Blessing of Sanctuary");
static_spell greater_blessing_of_might("Greater Blessing of Might");
static_spell judgement_of_wisdom_spell("Judgement of Wisdom");
static_spell judgement_of_justice("Judgement of Justice");
static_spell avengers_shield_spell("Avenger's Shield");
static_spell shield_of_righteousness_spell("Shield of Righteousness");
static_spell hammer_of_the_righteous_spell("Hammer of the Righteous");
static_spell call_pet_spell("Call Pet");
static_spell revive_pet_spell("Revive Pet");
static_spell mend_pet_spell("Mend Pet");
static_spell aspect_of_the_viper_spell("Aspect of the Viper");
static_spell aspect_of_the_dragonhawk_spell("Aspect of the Dragonhawk");
static_spell trueshot_aura("Trueshot Aura");
static_spell aspect_of_the_hawk_spell("Aspect of the Hawk");
static_spell serpent_sting_spell("Serpent Sting");
static_spell arcane_shot_spell("Arcane Shot");
static_spell hunters_mark_spell("Hunter's Mark");
static_spell concussive_shot_spell("Concussive Shot");
static_spell multishot_spell("Multi-Shot");
static_spell kill_command_spell("Kill Command");
static_spell mongoose_bite_spell("Mongoose Bite");
static_spell raptor_strike_spell("Raptor Strike");
static_spell bloodrage_spell("Bloodrage");
static_spell intercept_spell("Intercept");
static_spell commanding_shout_spell("Commanding Shout");
static_spell slam_aura("Slam!");
static_spell slam_spell_casted("Slam");
static_spell heroic_strike_spell("Heroic Strike");
static_spell mocking_blow_spell("Mocking Blow");
static_spell thunder_clap_spell("Thunder Clap");
static_spell sword_and_board_spell("Sword and Board");
static_spell cleave_spell("Cleave");
static_spell whirlwind_spell("Whirlwind");
static_spell berserker_stance("Berserker Stance");
static_spell defensive_stance("Defensive Stance");
static_spell battle_stance("Battle Stance");
static_spell sweeping_strikes_spell("Sweeping Strikes");
static_spell devastate_spell("Devastate");
static_spell bloodthirst_spell("Bloodthirst");
static_spell victory_rush_spell("Victory Rush");
static_spell deathwish_spell("Death Wish");
static_spell recklessness_spell("Recklessness");
static_spell rend_spell("Rend");
static_spell charge_spell("Charge");
static_spell disarm_spell("Disarm");
static_spell execute_spell("Execute");
static_spell overpower_spell("Overpower");
static_spell battle_shout_spell("Battle Shout");
static_spell taunt_spell("Taunt");
static_spell revenge_spell("Revenge");
static_spell revenge_aura("Revenge!");
static_spell shield_slam_spell("Shield Slam");
static_spell shield_bash_spell("Shield Bash");
static_spell concussion_blow_spell("Concussion Blow");
static_spell shield_block_spell("Shield Block");
static_spell mortal_strike_spell("Mortal Strike");
static_spell shockwave_spell("Shockwave");
static_spell sunder_armor("Sunder Armor");
static_spell moonkin_form_aura("Moonkin Form");
static_spell wrath_spell("Wrath");
static_spell starfall_spell("Starfall");
static_spell faerie_fire_spell("Faerie Fire");
static_spell faerie_fire_feral_spell("Faerie Fire (Feral)");
static_spell moonfire_spell("Moonfire");
static_spell insect_swarm_spell("Insect Swarm");
static_spell eclipse_lunar_aura("Eclipse (Lunar)");
static_spell starfire_spell("Starfire");
static_spell eclipse_solar_aura("Eclipse (Solar)");
static_spell vampiric_touch_spell("Vampiric Touch");
static_spell devouring_plague_spell("Devouring Plague");
static_spell mind_blast_spell("Mind Blast");
static_spell mind_sear_spell("Mind Sear");
static_spell mind_flat_spell("Mind Flay");
static_spell seal_of_wisdom_spell("Seal of Wisdom");
static_spell blessing_of_wisdom_spell("Blessing of Wisdom");
static_spell greater_blessing_of_wisdom_spell("Greater Blessing of Wisdom");
static_spell beacon_of_light_spell("Beacon of Light");
static_spell water_shield_spell("Water Shield");
static_spell lightning_shield_spell("Lightning Shield");
static_spell earth_shield_spell("Earth Shield");
static_spell lay_on_hands_spell("Lay on Hands");
static_spell holy_shock_spell("Holy Shock");
static_spell flash_of_light_spell("Flash of Light");
static_spell holy_light_spell("Holy Light");
static_spell weakened_soul_aura("Weakened Soul");
static_spell power_word_shield_spell("Power Word: Shield");
static_spell vampiric_embrace("Vampiric Embrace");
static_spell pain_supression("Pain Suppression");
static_spell penance("Penance");
static_spell inner_focus("Inner Focus");
static_spell prayer_of_mending_spell("Prayer of Mending");
static_spell flash_heal_spell("Flash Heal");
static_spell prayer_of_healing_spell("Prayer of Healing");
static_spell binding_heal_spell("Binding Heal");
static_spell priest_lesser_heal_spell("Lesser Heal");
static_spell renew_spell("Renew");
static_spell mind_blast("Mind Blast");
static_spell mind_flay("Mind Flay");
static_spell shadow_word_pain("Shadow Word: Pain");
static_spell shadow_word_death("Shadow Word: Death");
static_spell devouring_plague("Devouring Plague");
static_spell natures_swiftness_spell("Nature's Swiftness");
static_spell healing_wave_spell("Healing Wave");
static_spell chain_heal_spell("Chain Heal");
static_spell riptide_spell("Riptide");
static_spell lesser_healing_wave_spell("Lesser Healing Wave");
static_spell lightning_bolt_spell("Lightning Bolt");
static_spell chain_lightning_spell("Chain Lightning");
static_spell thunderstorm_spell("Thunderstorm");
static_spell lavaburst_spell("Lava Burst");
static_spell rejuvenation_spell("Rejuvenation");
static_spell regrowth_spell("Regrowth");
static_spell nourish_spell("Nourish");
static_spell clearcasting_spell("Clearcasting");
static_spell tree_of_life_form("Tree of Life");
static_spell healing_touch_spell("Healing Touch");
static_spell wild_growth_spell("Wild Growth");
static_spell swiftmend_spell("Swiftmend");
static_spell lifebloom_spell("Lifebloom");
static_spell flame_shock_spell("Flame Shock");
static_spell earth_shock_spell("Earth Shock");
static_spell molten_armor_spell("Molten Armor");
static_spell arcane_intellect_spell("Arcane Intellect");
static_spell fire_blast_spell("Fire Blast");
static_spell fireball_spell("Fireball");
static_spell demon_armor_spell("Demon Armor");
static_spell fel_armor_spell("Fel Armor");
static_spell shadow_mastery_aura("Shadow Mastery");
static_spell immolate_spell("Immolate");
static_spell corruption_spell("Corruption");
static_spell seed_of_corruption_spell("Seed of Corruption");
static_spell unstable_affliction_spell("Unstable Affliction");
static_spell haunt_spell("Haunt");
static_spell curse_of_agony_spell("Curse of Agony");
static_spell curse_of_weakness_spell("Curse of Weakness");
static_spell curse_of_elements_spell("Curse of the Elements");
static_spell earth_and_moon_aura("Earth and Moon");
static_spell ebon_plaguebringer_spell("Ebon Plaguebringer");
static_spell life_tap_spell("Life Tap");
static_spell drain_soul_spell("Drain Soul");
static_spell shadowbolt_spell("Shadow Bolt");
static_spell prowl_spell("Prowl");
static_spell ravage_spell("Ravage");
static_spell tigers_fury_spell("Tiger's Fury");
static_spell berserk_spell("Berserk");
static_spell savage_roar_spell("Savage Roar");
static_spell mangle_cat_spell("Mangle (Cat)");
static_spell rake_spell("Rake");
static_spell rip_spell("Rip");
static_spell ferocious_bite_spell("Ferocious Bite");
static_spell claw_spell("Claw");
static_spell shred_spell("Shred");
static_spell cower_spell("Cower");
static_spell growl_spell("Growl");
static_spell demoralizing_shout_spell("Demoralizing Shout");
static_spell demoralizing_roar_spell("Demoralizing Roar");
static_spell maul_spell("Maul");
static_spell mangle_bear_spell("Mangle (Bear)");
static_spell lacerate_spell("Lacerate");
static_spell enrage_spell("Enrage");
static_spell swipe_bear_spell("Swipe (Bear)");
static_spell swipe_spell("Swipe (Bear)");
static_spell swipe_cat_spell("Swipe (Cat)");
static_spell cat_form_aura("Cat Form");
static_spell bear_form_aura("Bear Form");
static_spell prowl("Prowl");
static_spell dire_bear_form_aura("Dire Bear Form");
static_spell raise_dead_spell("Raise Dead");
static_spell horn_of_winter_spell("Horn of Winter");
static_spell blood_presence_aura("Blood Presence");
static_spell unholy_presence_aura("Unholy Presence");
static_spell bone_shield_spell("Bone Shield");
static_spell blood_plague_aura("Blood Plague");
static_spell frost_fever_aura("Frost Fever");
static_spell blood_tap_spell("Blood Tap");
static_spell empower_rune_weapon_spell("Empower Rune Weapon");
static_spell plague_strike_spell("Plague Strike");
static_spell icy_touch_spell("Icy Touch");
static_spell desolation_aura("Desolation");
static_spell blood_strike_spell("Blood Strike");
static_spell scourge_strike_spell("Scourge Strike");
static_spell death_coil_spell("Death Coil");
static_spell summon_gargoyle_spell("Summon Gargoyle");
static_spell freezing_fog_aura("Freezing Fog");
static_spell death_chill_spell("Deathchill");
static_spell howling_blast_spell("Howling Blast");
static_spell frost_strike_spell("Frost Strike");
static_spell pestilence_spell("Pestilence");
static_spell blood_boil_spell("Blood Boil");
static_spell unbreakable_armor_spell("Unbreakable Armor");
static_spell obliterate_spell("Obliterate");
static_spell death_strike_spell("Death Strike");
static_spell trauma_aura("Trauma");
static_spell hot_streak_aura("Hot Streak");
static_spell combustion_spell("Combustion");
static_spell pyroblast_spell("Pyroblast");
static_spell living_bomb_spell("Living Bomb");
static_spell improved_scorch_aura("Improved Scorch");
static_spell scorch_spell("Scorch");
static_spell fire_vulnerability_aura("Fire Vulnerability");
static_spell frost_armor_spell("Frost Armor");
static_spell shadow_dance_aura("Shadow Dance");
static_spell garrote_aura("Garrote");
static_spell stealth_aura("Stealth");
static_spell shadowform_aura("Shadowform");
static_spell ambush_spell("Ambush");
static_spell slice_and_dice_spell("Slice and Dice");
static_spell tricks_of_the_trade_spell("Tricks of the Trade");
static_spell rupture_spell("Rupture");
static_spell expose_armor_spell("Expose Armor");
static_spell garrote_spell("Garrote");
static_spell envenom_spell("Envenom");
static_spell cold_blood_spell("Cold Blood");
static_spell fan_of_knives("Fan of Knives");
static_spell hunger_for_blood_spell("Hunger For Blood");
static_spell mutilate_spell("Mutilate");
static_spell hemorrhage_spell("Hemorrhage");
static_spell backstab_spell("Backstab");
static_spell eviscerate_spell("Eviscerate");
static_spell sinister_strike_spell("Sinister Strike");
static_spell judgements_of_the_pure_aura("Judgements of the Pure");
static_spell ghoul_frenzy_spell("Ghoul Frenzy");
static_spell feral_attack_spell("Feral Attack");

static_spell shield_spell("Power Word: Shield");    
static_spell weak_soul("Weakened Soul");            
static_spell pom("Prayer of Mending");              
static_spell flash_heal("Flash Heal");              
static_spell greater_heal_spell("Greater Heal");          
static_spell poh("Prayer of Healing");              
static_spell binding_heal("Binding Heal");          
static_spell priest_heal("Heal"); 


static_spell remove_curse_spell("Remove Curse");
static_spell lucifroncurse("Curse of Lucifron");
static_spell gehennascurse("Curse of Gehennas");
static_spell ancientdispaircurse("Ancient Despair");
static_spell ancientfurycurse("Ancient Fury");
static_spell ancienthysteriacurse("Ancient Hysteria");
static_spell veilofshadowcurse("Veil of Shadow");
static_spell ancientdreadcurse("Ancient Dread");
static_spell shrinkcurse("Shrink");
static_spell curseofblood("Curse of Blood");
static_spell curseofvulnerabilitycurse("Curse of Vulnerability");
static_spell curseoftonguescurse("Curse of Tongues");
static_spell callofthegrave("Call of the Grave");
static_spell mortalpoison("Mortal Poison");
static_spell abolish_poison("Abolish Poison");

static_spell riptide("Riptide");                    
static_spell chain_heal("Chain Heal");              
static_spell lhw("Lesser Healing Wave");            
static_spell hw("Healing Wave");                    
static_spell earth_shield("Earth Shield");          
static_spell ns("Nature's Swiftness");              

static_spell rejuv("Rejuvenation");                 
static_spell regrowth("Regrowth");                  
static_spell lifebloom("Lifebloom");                
static_spell wild_growth("Wild Growth");            
static_spell nourish("Nourish");                    
static_spell swiftmend("Swiftmend");                
static_spell ascension_checker("PvE Mode");
static_spell infusion_of_light_spell("Infusion of Light");
static_spell desperate_prayer("Desperate Prayer");
static_spell healing_wave("Healing Wave");
static_spell lesser_healing_wave("Lesser Healing Wave");
static_spell divine_favor_spell("Divine Favor");
static_spell borrowed_time_spell("Borrowed Time");
static_spell pain_suppression_spell("Pain Suppression");
static_spell inner_focus_spell("Inner Focus");
static_spell barkskin_spell("Barkskin");
static_spell holy_fire_spell("Holy Fire");
static_spell smite_spell("Smite");
static_spell inner_fire_spell("Inner Fire");
static_spell divine_spirit("Divine Spirit");
static_spell halo_spell("Halo");

static_spell water_nova("Water Nova");
static_spell frost_shock_spell("Frost Shock");
static_spell burn_through_spell("Melt Through");
static_spell booming_thunder("Booming Thunder");